FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .


RUN chmod +x init.sh && \
    sed -i 's/\r$//' init.sh


ENV FLASK_APP=app.py
ENV FLASK_ENV=development
ENV PYTHONPATH=/app

EXPOSE 5000


CMD ["./init.sh"]