# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt requirements.txt

# Обновляем pip и устанавливаем зависимости
RUN apt-get update && apt-get install -y libpq-dev
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Копируем исходный код приложения
COPY . .

# Указываем порт, на котором работает приложение
EXPOSE 5000

# Команда запуска приложения
CMD ["python", "routes.py"]
